// Independent native-app check: real PDF translation, persistence and deletion.
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { _electron } = require('playwright');
const { spawnSync } = require('node:child_process');
const { createToolsFixture } = require('./fixture_tools_api.cjs');
const root = path.resolve(__dirname, '..');
const output = path.join(root, '.review', `pdf-layout-${Date.now()}`);
const source = path.join(root, '.review', 'fixtures', 'layout_images.pdf');
const dataRoot = path.join(output, 'data');
const temp = path.join(output, 'temp');
fs.mkdirSync(temp, { recursive: true });
const hash = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const originalHash = hash(source);
const referenceCache = 'C:\\Users\\17919\\.cache\\babeldoc\\cache.v1.db';
const cacheFingerprint = () => fs.existsSync(referenceCache) ? hash(referenceCache) : null;
const originalCacheFingerprint = cacheFingerprint();

(async () => {
  let application;
  const fixture = await createToolsFixture();
  const errors = [];
  const started = Date.now();
  try {
    const env = { ...process.env, WORKBENCH_DATA_DIR: dataRoot, TEMP: temp, TMP: temp };
    delete env.ELECTRON_RUN_AS_NODE;
    delete env.WORKBENCH_FREE_API_URL;
    delete env.WORKBENCH_FREE_TRANSLATION_URL;
    delete env.WORKBENCH_TRANSLATION_URL;
    const options = { cwd: root, env, timeout: 90000 };
    if (process.env.REVIEW_EXECUTABLE) Object.assign(options, { executablePath: process.env.REVIEW_EXECUTABLE, args: [] });
    else Object.assign(options, { executablePath: path.join(root, 'node_modules', 'electron', 'dist', 'electron.exe'), args: ['.'] });
    application = await _electron.launch(options);
    const version = await application.evaluate(({ app }) => app.getVersion());
    assert.equal(version, '0.11.0');
    let main = await application.firstWindow();
    main.on('pageerror', error => errors.push(error.message));
    await main.getByRole('button', { name: 'AI 设置', exact: true }).waitFor();
    const settings = await main.evaluate(() => window.workbench.request({ path: '/settings' }));
    assert.equal(settings.key_configured, false);
    assert.equal(settings.base_url, '');
    await application.evaluate(({ dialog }, source) => {
      dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [source] });
    }, source);
    await main.getByRole('button', { name: /导入文献/ }).click();
    let paper;
    const deadline = Date.now() + 900000;
    while (Date.now() < deadline) {
      const papers = await main.evaluate(() => window.workbench.request({ path: '/papers' }));
      paper = papers.find(value => value.source_name === 'layout_images.pdf');
      if (paper?.can_read) break;
      if (paper?.status === 'error' || paper?.status === 'needs_attention') throw new Error(paper.error);
      await new Promise(resolve => setTimeout(resolve, 750));
    }
    assert.ok(paper?.can_read, 'Actual translated PDFs must exist before reading');
    assert.match(paper.chinese_title, /[\u4e00-\u9fff]/);
    assert.equal(paper.api_tokens || 0, 0);
    const folder = path.join(dataRoot, 'papers', paper.id);
    const files = fs.readdirSync(folder).filter(name => name.toLowerCase().endsWith('.pdf'));
    assert.ok(files.length >= 3, 'original, Chinese, bilingual PDFs must be retained');
    for (const name of files) assert.equal(fs.readFileSync(path.join(folder, name)).subarray(0, 5).toString(), '%PDF-');
    const evidence = path.join(output, 'pdfs');
    fs.mkdirSync(evidence);
    for (const name of files) fs.copyFileSync(path.join(folder, name), path.join(evidence, name));
    fs.writeFileSync(path.join(output, 'paper.json'), JSON.stringify({ paper, files, source, folder }, null, 2));
    await main.locator('.paper-card').filter({ hasText: source.split(path.sep).at(-1) }).getByRole('button', { name: '阅读', exact: true }).click();
    let reader = main;
    assert.equal(application.windows().length, 1, 'Translated PDF must open as a workbench tab');
    await reader.getByLabel('向当前文献提问').waitFor();
    await reader.locator('.pdf-page-stage > canvas').first().waitFor({ timeout: 30000 });
    await reader.locator('.textLayer').getByText(/137/).first().waitFor({ timeout: 30000 });
    const canvasBox = await reader.locator('.pdf-page-stage > canvas').first().evaluate(canvas => ({ width: canvas.width, height: canvas.height }));
    assert.ok(canvasBox.width/canvasBox.height > 1.3, 'default reader must display the actual wide bilingual PDF');
    await reader.screenshot({ path: path.join(output, 'bilingual-reader.png') });
    await reader.getByRole('button', { name: '中文 PDF', exact: true }).click();
    await reader.waitForFunction(() => {
      const canvas = document.querySelector('.pdf-page-stage > canvas');
      return canvas && canvas.width/canvas.height < 1 && /[\u4e00-\u9fff]/.test(document.querySelector('.textLayer')?.textContent || '');
    }, undefined, { timeout: 30000 });
    await reader.locator('.textLayer').getByText(/137/).first().waitFor({ timeout: 30000 });
    await reader.screenshot({ path: path.join(output, 'chinese-reader.png') });
    await main.evaluate(address => window.workbench.request({ path: '/settings', method: 'PUT', body: { base_url: address, model: 'review-fixture', api_key: 'review-only-pdf-layout-key' } }), fixture.apiUrl);
    await reader.waitForFunction(() => document.querySelector('[data-testid=reader-model-select]')?.value === 'review-fixture');
    await reader.getByLabel('向当前文献提问').fill('详细总结一下这篇文献');
    await reader.getByRole('button', { name: /发送/ }).click();
    await reader.locator('.chat-message.assistant').first().waitFor({ timeout: 30000 });
    await reader.getByLabel('停止生成').waitFor({ state: 'hidden' });
    const summary = await reader.locator('.chat-message.assistant').first().innerText();
    for (const fact of ['137', '23.7', '811']) assert.ok(summary.includes(fact), `AI did not receive the paper fact ${fact}`);
    assert.equal(fixture.requests.length, 2, 'full summary must use one tool decision and one whole-paper prompt without synthesis');
    assert.ok(fixture.requests.every(request => request.path === fixture.requestPath && request.model === 'review-fixture' && request.stream === true));
    assert.ok(fixture.requests.some(request => request.messages.some(message => typeof message.content === 'string' && message.content.includes('137 independent samples'))));
    fs.writeFileSync(path.join(output, 'requests.json'), JSON.stringify(fixture.requests, null, 2));
    await reader.getByRole('button', { name: '下一页', exact: true }).click();
    await reader.getByLabel('当前页码').waitFor();
    await new Promise(resolve => setTimeout(resolve, 600));
    const outputHashes = Object.fromEntries(files.map(name => [name, hash(path.join(folder, name))]));
    await application.close();
    application = await _electron.launch(options);
    main = await application.firstWindow();
    await main.getByRole('button', { name: 'AI 设置', exact: true }).waitFor();
    const persisted = await main.evaluate(id => window.workbench.request({ path: `/papers/${id}` }), paper.id);
    assert.equal(persisted.can_read, true);
    assert.equal(persisted.last_page, 2);
    for (const [name, digest] of Object.entries(outputHashes)) assert.equal(hash(path.join(folder, name)), digest);
    reader = main;
    await reader.getByLabel('向当前文献提问').waitFor();
    assert.equal(await reader.locator('.chat-message.assistant').count(), 1);
    assert.equal(fixture.requests.length, 2, 'restart must use persisted chat');
    // Endpoint deletion is also exercised by Python tests; native confirmation is checked here.
    await main.getByTestId('library-tab').click();
    const remove = main.locator('.paper-card').filter({ hasText: 'layout_images.pdf' }).getByRole('button', { name: '删除', exact: true });
    let confirmation = main.waitForEvent('dialog');
    let click = remove.click();
    let dialog = await confirmation;
    assert.match(dialog.message(), /源文件不会删除/);
    await dialog.dismiss();
    await click;
    assert.equal(fs.existsSync(folder), true, 'cancel must preserve the paper');
    confirmation = main.waitForEvent('dialog');
    click = remove.click();
    dialog = await confirmation;
    await dialog.accept();
    await click;
    await main.getByTestId(`paper-tab-${paper.id}`).waitFor({ state: 'detached' });
    assert.equal(application.windows().length, 1, 'Deleting a paper must keep the workbench open');
    assert.equal(fs.existsSync(folder), false);
    assert.equal(hash(source), originalHash);
    assert.equal(cacheFingerprint(), originalCacheFingerprint, 'workbench PDF translation must not write the reference server cache on C');
    assert.equal(errors.length, 0, errors.join('\n'));
    fs.writeFileSync(path.join(output, 'result.json'), JSON.stringify({ result: 'passed', seconds: (Date.now()-started)/1000, paper, files, outputHashes, errors }, null, 2));
    console.log(JSON.stringify({ result: 'passed', output }));
  } catch (error) {
    fs.writeFileSync(path.join(output, 'requests.json'), JSON.stringify(fixture.requests, null, 2));
    fs.writeFileSync(path.join(output, 'failure.txt'), String(error.stack || error));
    throw error;
  } finally {
    if (application) await application.close();
    await new Promise(resolve => fixture.server.close(resolve));
    const cleaned = spawnSync(path.join(root, '.venv', 'Scripts', 'python.exe'), ['-B', '-c', 'from backend.ai import credential_service; import keyring; service=credential_service(); keyring.delete_password(service,"api-key") if keyring.get_password(service,"api-key") else None'], { cwd: root, env: { ...process.env, WORKBENCH_DATA_DIR: dataRoot }, encoding: 'utf8' });
    if (cleaned.status !== 0) throw new Error('Test credential cleanup failed');
  }
})();
