// Independent native acceptance for continuous reading, sharp rendering and optional AI tools.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { _electron } = require('playwright');
const { createToolsFixture } = require('./fixture_tools_api.cjs');
const root = path.resolve(__dirname, '..');
const output = path.join(root, '.review', `reader-tools-${Date.now()}`);
const dataRoot = path.join(output, 'data');
const temp = path.join(output, 'temp');
fs.mkdirSync(temp, { recursive: true });
const prepared = spawnSync(path.join(root, '.venv/Scripts/python.exe'), ['-B', '-m', 'review.seed_reader_fixture', dataRoot, '--mixed'], { cwd: root, env: { ...process.env, WORKBENCH_DATA_DIR: dataRoot, TEMP: temp, TMP: temp, PYTHONIOENCODING: 'utf-8' }, encoding: 'utf8' });
assert.equal(prepared.status, 0, prepared.stderr);
const seeded = JSON.parse(prepared.stdout.trim());

(async () => {
  let application;
  const fixture = await createToolsFixture();
  const errors = [];
  const started = Date.now();
  try {
    const env = { ...process.env, WORKBENCH_DATA_DIR: dataRoot, TEMP: temp, TMP: temp };
    delete env.ELECTRON_RUN_AS_NODE;
    delete env.WORKBENCH_DEV;
    const options = { cwd: root, env, timeout: 90000 };
    if (process.env.REVIEW_EXECUTABLE) Object.assign(options, { executablePath: process.env.REVIEW_EXECUTABLE, args: ['--force-device-scale-factor=1.5'] });
    else Object.assign(options, { executablePath: path.join(root, 'node_modules/electron/dist/electron.exe'), args: ['.', '--force-device-scale-factor=1.5'] });
    application = await _electron.launch(options);
    const version = await application.evaluate(({ app }) => app.getVersion());
    if (process.env.REVIEW_EXECUTABLE) assert.equal(version, '0.12.0');
    let main = await application.firstWindow();
    main.on('pageerror', error => errors.push(error.message));
    await main.getByRole('button', { name: '设置', exact: true }).waitFor();
    await main.evaluate(address => window.workbench.request({ path: '/settings', method: 'PUT', body: { base_url: address, protocol: 'custom_chat_completions', model: 'fixture-A', api_key: 'review-only-tools-key' } }), fixture.apiUrl);
    await main.evaluate(() => window.workbench.request({ path: '/settings/models', method: 'PUT', body: { models: ['fixture-A', 'fixture-B'] } }));
    await application.evaluate(({ ipcMain }) => {
      const request = ipcMain._invokeHandlers.get('workbench:request');
      globalThis.__reviewPdfLoads = [];
      ipcMain.removeHandler('workbench:request');
      ipcMain.handle('workbench:request', (event, input) => {
        if (input.binary && input.path.includes('/pdf')) globalThis.__reviewPdfLoads.push(input.path);
        return request(event, input);
      });
    });
    await main.locator('.paper-card').getByRole('button', { name: '阅读', exact: true }).click();
    let reader = main;
    assert.equal(application.windows().length, 1, 'Reader must be a workbench tab');
    await reader.locator('[data-testid=pdf-scroll]').waitFor();
    await reader.locator('canvas[data-page-number="1"]').waitFor();
    await reader.waitForFunction(() => {
      const canvas = document.querySelector('canvas[data-page-number="1"]');
      return canvas && canvas.width > 0 && document.querySelector('.textLayer')?.textContent.includes('137');
    });
    assert.equal(await reader.locator('.pdf-page-frame').count(), 12);
    const portraitFrame = await reader.locator('.pdf-page-frame[data-page-number="1"]').boundingBox();
    const rotatedFrame = await reader.locator('.pdf-page-frame[data-page-number="3"]').boundingBox();
    assert.ok(rotatedFrame.height > portraitFrame.height * 1.8, 'Each mixed-size page must reserve its own viewport geometry before rendering');
    const sharpness = await reader.locator('canvas[data-page-number="1"]').evaluate(canvas => ({ bitmapWidth: canvas.width, cssWidth: parseFloat(canvas.style.width), dpr: window.devicePixelRatio }));
    assert.ok(sharpness.bitmapWidth / sharpness.cssWidth >= 1.99, 'Canvas must supersample; source PDF must not be shown at one bitmap pixel per CSS pixel');
    const topBefore = await reader.locator('.reading-toolbar').boundingBox();
    const scroll = reader.locator('[data-testid=pdf-scroll]');
    const settleAtPage = async target => {
      await reader.waitForFunction(number => {
        const root = document.querySelector('[data-testid=pdf-scroll]');
        const frame = document.querySelector(`.pdf-page-frame[data-page-number="${number}"]`);
        if (!root || !frame || document.querySelector('[aria-label="当前页码"]')?.value !== String(number)) return false;
        const page = frame.getBoundingClientRect();
        const viewport = root.getBoundingClientRect();
        return page.top < viewport.bottom - 80 && page.bottom > viewport.top + 80;
      }, target);
      await new Promise(resolve => setTimeout(resolve, 400));
      assert.equal(await reader.getByLabel('当前页码').inputValue(), String(target), 'Navigation must remain on the requested page after scroll observers settle');
    };
    const scrollBox = await scroll.boundingBox();
    await reader.mouse.move(scrollBox.x + scrollBox.width / 2, scrollBox.y + scrollBox.height / 2);
    await reader.mouse.wheel(0, 1400);
    await reader.waitForFunction(() => Number(document.querySelector('[aria-label="当前页码"]').value) >= 3);
    const topAfter = await reader.locator('.reading-toolbar').boundingBox();
    assert.ok(Math.abs(topBefore.y - topAfter.y) < 1, 'Zoom toolbar must remain fixed while reading further pages');
    assert.ok(await reader.locator('[aria-label="放大 PDF"]').isVisible());
    await reader.getByLabel('放大 PDF').click();
    await reader.waitForFunction(() => document.querySelector('.zoom-controls')?.textContent.includes('110%'));
    await reader.locator('.page-index').last().click();
    await settleAtPage(12);
    await reader.waitForFunction(() => document.querySelector('canvas[data-page-number="12"]')?.width > 0);
    const activeCanvases = await reader.locator('canvas[data-page-number]').evaluateAll(canvases => canvases.filter(canvas => canvas.width > 0 && canvas.height > 0).length);
    assert.ok(activeCanvases < 12, 'Far pages must release their bitmap memory');
    const pdfLoads = await application.evaluate(() => globalThis.__reviewPdfLoads);
    assert.equal(pdfLoads.length, 1, 'Twelve pages and zoom must share a single loaded PDF');
    const heightAfterFirstPass = await scroll.evaluate(element => element.scrollHeight);
    await reader.locator('.page-index').first().click();
    await settleAtPage(1);
    await reader.waitForFunction(() => document.querySelector('canvas[data-page-number="1"]')?.width > 0);
    assert.ok(Math.abs(await scroll.evaluate(element => element.scrollHeight) - heightAfterFirstPass) < 3, 'Mixed-size page placeholders must retain their exact heights when canvases are released');
    await reader.locator('.page-index').last().click();
    await settleAtPage(12);
    await reader.screenshot({ path: path.join(output, 'continuous-reader.png') });
    const model = reader.locator('[data-testid=reader-model-select]');
    await main.getByRole('button', { name: '设置', exact: true }).click();
    await main.locator('.advanced-manual-model > summary').click();
    await main.getByLabel('添加模型', { exact: true }).fill('fixture-C');
    await main.getByRole('button', { name: '手动添加', exact: true }).click();
    await main.locator('.saved-model-list').getByText('fixture-C', { exact: true }).waitFor();
    await main.getByTestId(`paper-tab-${seeded.paper_id}`).click();
    assert.equal(await reader.getByTestId('reader-model-input').count(), 0);
    await model.selectOption('fixture-C');
    await reader.waitForFunction(() => document.querySelector('[data-testid=reader-model-select]')?.value === 'fixture-C');
    await model.selectOption('fixture-B');
    await reader.waitForFunction(() => document.querySelector('[data-testid=reader-model-select]')?.value === 'fixture-B');
    await reader.getByLabel('向当前文献提问').fill('2+2是多少');
    await reader.getByRole('button', { name: /发送/ }).click();
    let assistant = reader.locator('.chat-message.assistant').last();
    await assistant.locator('h2').waitFor();
    await reader.getByLabel('停止生成').waitFor({ state: 'hidden' });
    assert.equal(fixture.requests.length, 1, 'Ordinary chat must not retrieve paper text or request an extra classification');
    const firstRequest = fixture.requests[0];
    assert.equal(firstRequest.model, 'fixture-B');
    assert.equal(firstRequest.tool_choice, 'auto');
    assert.ok(firstRequest.tools.some(tool => tool.function.name === 'read_paper'));
    assert.ok(firstRequest.messages.every(message => typeof message.content === 'string'));
    assert.ok(!JSON.stringify(firstRequest.messages).includes('137 independent samples'));
    assert.equal(await assistant.locator('strong').count(), 1);
    assert.equal(await assistant.locator('table').count(), 1);
    assert.equal(await assistant.locator('pre code').count(), 1);
    assert.equal(await assistant.locator('ul li').count(), 2);
    assert.equal(await assistant.locator('script, img').count(), 0);
    assert.equal(await reader.evaluate(() => Boolean(window.__markdownUnsafe)), false);
    await reader.screenshot({ path: path.join(output, 'markdown-chat.png') });
    await reader.getByLabel('向当前文献提问').fill('这篇文献的样本是多少');
    await reader.getByRole('button', { name: /发送/ }).click();
    await reader.waitForFunction(() => document.querySelectorAll('.chat-message.assistant').length === 2);
    await reader.getByLabel('停止生成').waitFor({ state: 'hidden' });
    assert.equal(fixture.requests.length, 3, 'Reading must be one model tool decision followed by one answer');
    const calls = fixture.requests.slice(1);
    assert.ok(calls.every(request => request.model === 'fixture-B'));
    assert.ok(!JSON.stringify(calls[0].messages).includes('137 independent samples'));
    const toolMessage = calls[1].messages.find(message => message.role === 'tool');
    assert.ok(toolMessage && toolMessage.content.includes('137 independent samples'));
    assert.ok(!JSON.stringify(toolMessage).includes('image_url'));
    assistant = reader.locator('.chat-message.assistant').last();
    await assistant.locator('.citation-button').first().click();
    await reader.waitForFunction(() => document.querySelector('[aria-label="当前页码"]').value !== '12');
    await reader.locator('.page-index').last().click();
    await settleAtPage(12);
    await reader.getByLabel('向当前文献提问').fill('详细总结一下这篇文献');
    await reader.getByRole('button', { name: /发送/ }).click();
    await reader.waitForFunction(() => document.querySelectorAll('.chat-message.assistant').length === 3, undefined, { timeout: 60000 });
    await reader.getByLabel('停止生成').waitFor({ state: 'hidden' });
    assert.equal(fixture.requests.length, 5, 'Summary adds only one tool decision and one whole-paper request');
    const fullPrompt = fixture.requests.at(-1);
    assert.equal(fullPrompt.tools, undefined, 'Whole-paper answer must not start another tool loop');
    assert.ok(fullPrompt.messages.some(message => typeof message.content === 'string' && message.content.includes('137 independent samples') && message.content.includes('811')));
    assert.ok(fullPrompt.messages.every(message => typeof message.content === 'string'), 'PDF must enter the prompt as text, never images');
    const requestsBeforeRestart = fixture.requests.length;
    assert.ok(fixture.requests.at(-2).tools?.some(tool => tool.function.name === 'summarize_paper'));
    assert.ok(fixture.requests.every(request => request.path === fixture.requestPath && request.model === 'fixture-B' && request.stream === true));
    await new Promise(resolve => setTimeout(resolve, 800));
    await application.close();
    application = await _electron.launch(options);
    await application.evaluate(({ dialog }, file) => {
      dialog.showMessageBox = async options => {
        require('node:fs').appendFileSync(file, JSON.stringify(options) + '\n');
        return { response: 0 };
      };
    }, path.join(output, 'startup-dialogs.jsonl'));
    main = await application.firstWindow();
    await main.getByRole('button', { name: '设置', exact: true }).waitFor();
    reader = main;
    await reader.locator('[data-testid=reader-model-select]').waitFor();
    await reader.waitForFunction(() => document.querySelector('[aria-label="当前页码"]')?.value === '12');
    assert.equal(await reader.locator('[data-testid=reader-model-select]').inputValue(), 'fixture-B');
    assert.equal(await reader.locator('.chat-message.assistant').count(), 3);
    assert.equal(fixture.requests.length, requestsBeforeRestart);
    assert.equal(errors.length, 0, errors.join('\n'));
    fs.writeFileSync(path.join(output, 'requests.json'), JSON.stringify(fixture.requests, null, 2));
    fs.writeFileSync(path.join(output, 'result.json'), JSON.stringify({ result: 'passed', version, seconds: (Date.now()-started)/1000, seeded, sharpness, activeCanvases, pdfLoads, requests: fixture.requests.length, errors }, null, 2));
    console.log(JSON.stringify({ result: 'passed', output }));
  } catch (error) {
    fs.writeFileSync(path.join(output, 'failure.txt'), String(error.stack || error));
    throw error;
  } finally {
    if (application) await application.close();
    await new Promise(resolve => fixture.server.close(resolve));
    const cleaned = spawnSync(path.join(root, '.venv/Scripts/python.exe'), ['-B', '-c', 'from backend.ai import credential_service; import keyring; service=credential_service(); keyring.delete_password(service,"api-key") if keyring.get_password(service,"api-key") else None'], { cwd: root, env: { ...process.env, WORKBENCH_DATA_DIR: dataRoot }, encoding: 'utf8' });
    if (cleaned.status !== 0) throw new Error('Test credential cleanup failed');
  }
})();
