// Independent native checks: pane resizing, hidden live chat, automatic models.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { _electron } = require('playwright');
const { createStreamFixture } = require('./fixture_stream_api.cjs');
const root = path.resolve(__dirname, '..');
const output = path.join(root, '.review', `layout-models-${Date.now()}`);
const dataRoot = path.join(output, 'data');
const temp = path.join(output, 'temp');
fs.mkdirSync(temp, { recursive: true });
const prepared = spawnSync(path.join(root, '.venv/Scripts/python.exe'), ['-B', '-m', 'review.seed_reader_fixture', dataRoot, '--mixed'], { cwd: root, env: { ...process.env, WORKBENCH_DATA_DIR: dataRoot, TEMP: temp, TMP: temp, PYTHONIOENCODING: 'utf-8' }, encoding: 'utf8' });
assert.equal(prepared.status, 0, prepared.stderr);
const seeded = JSON.parse(prepared.stdout.trim());
const delay = time => new Promise(resolve => setTimeout(resolve, time));

(async () => {
  let application;
  const fixture = await createStreamFixture();
  const errors = [];
  const pdfLoads = [];
  const started = Date.now();
  try {
    const env = { ...process.env, WORKBENCH_DATA_DIR: dataRoot, TEMP: temp, TMP: temp };
    delete env.ELECTRON_RUN_AS_NODE;
    delete env.WORKBENCH_DEV;
    const options = { cwd: root, env, timeout: 90000, executablePath: process.env.REVIEW_EXECUTABLE || path.join(root, 'node_modules/electron/dist/electron.exe'), args: process.env.REVIEW_EXECUTABLE ? [] : ['.'] };
    application = await _electron.launch(options);
    assert.equal(await application.evaluate(({ app }) => app.getVersion()), require(path.join(root, 'package.json')).version);
    assert.equal(await application.evaluate(({ app }) => app.getPath('userData')), path.join(dataRoot, 'electron-userData'));
    let main = await application.firstWindow();
    main.on('pageerror', error => errors.push(error.message));
    await main.getByRole('button', { name: '设置', exact: true }).waitFor();
    assert.equal((await main.locator('.brand-wordmark').textContent()).trim(), 'Folio');
    await main.waitForFunction(() => {
      const mark = document.querySelector('.brand-mark');
      const image = mark?.tagName === 'IMG' ? mark : mark?.querySelector('img');
      return image ? image.complete && image.naturalWidth > 0 : Boolean(mark?.querySelector('svg'));
    });
    await main.screenshot({ path: path.join(output, 'library.png') });
    await main.getByRole('button', { name: '设置', exact: true }).click();
    const apiUrl = main.locator('#base-url');
    const origin = new URL(fixture.apiUrl).origin;
    await apiUrl.fill(origin + '/v1');
    assert.ok(!(await main.getByLabel('模型列表地址', { exact: true }).isVisible()), 'A second URL field must not be required by default');
    await main.getByRole('button', { name: '获取模型列表', exact: true }).click();
    await main.getByRole('checkbox', { name: 'stream-fixture', exact: true }).waitFor();
    assert.deepEqual(fixture.modelRequests, [{ path: '/v1/models', authorized: false }]);
    let settings = await main.evaluate(() => window.workbench.request({ path: '/settings' }));
    assert.equal(settings.base_url, '');
    assert.equal(settings.model, '');
    assert.equal(settings.key_configured, false);
    await main.getByRole('checkbox', { name: 'stream-fixture', exact: true }).check();
    await main.getByRole('checkbox', { name: 'fixture-B', exact: true }).check();
    await main.getByRole('button', { name: '添加所选模型', exact: true }).click();
    await apiUrl.fill(fixture.apiUrl);
    await main.getByLabel('API 协议').selectOption('custom_chat_completions');
    const defaultModel = main.getByLabel('默认模型', { exact: true });
    if (await defaultModel.evaluate(element => element.tagName === 'SELECT')) await defaultModel.selectOption('stream-fixture');
    else await defaultModel.fill('stream-fixture');
    await main.getByLabel('AI API Key', { exact: true }).fill('review-only-layout-key');
    await main.getByRole('button', { name: '保存设置', exact: true }).click();
    await main.getByRole('button', { name: '获取模型列表', exact: true }).waitFor();
    await main.evaluate(address => window.workbench.request({ path: '/settings', method: 'PUT', body: { base_url: address, protocol: 'custom_chat_completions', model: 'stream-fixture', models_url: new URL('/obsolete/catalog', address).toString() } }), fixture.apiUrl);
    await main.getByTestId('library-tab').click();
    await main.getByRole('button', { name: '设置', exact: true }).click();
    await apiUrl.waitFor();
    await main.waitForFunction(address => document.querySelector('#base-url')?.value === address, fixture.apiUrl);
    await main.getByRole('button', { name: '获取模型列表', exact: true }).click();
    await main.getByRole('checkbox', { name: 'mimo-v6pro', exact: true }).waitFor();
    await main.getByRole('button', { name: '获取模型列表', exact: true }).waitFor();
    assert.deepEqual(fixture.modelRequests.at(-1), { path: '/literal/stream-endpoint/models?routing=test%2Bstream', authorized: true });
    await main.getByRole('checkbox', { name: 'mimo-v6pro', exact: true }).check();
    await main.getByRole('button', { name: '添加所选模型', exact: true }).click();
    await main.locator('.advanced-manual-model > summary').click();
    await main.getByLabel('添加模型', { exact: true }).fill('manual-layout-model');
    await main.getByRole('button', { name: '手动添加', exact: true }).click();
    await main.locator('.saved-model-list').getByText('manual-layout-model', { exact: true }).waitFor();
    settings = await main.evaluate(() => window.workbench.request({ path: '/settings' }));
    assert.equal(settings.base_url, fixture.apiUrl, 'Discovering models must preserve the literal chat URL');
    assert.equal(settings.model, 'stream-fixture');
    assert.deepEqual(settings.model_options, ['stream-fixture', 'fixture-B', 'mimo-v6pro', 'manual-layout-model']);
    await main.evaluate(() => window.scrollTo(0, 0));
    await main.screenshot({ path: path.join(output, 'settings.png') });
    await main.getByTestId('library-tab').click();
    await application.evaluate(({ ipcMain }) => {
      const original = ipcMain._invokeHandlers.get('workbench:request');
      globalThis.__reviewPdfLoads = [];
      ipcMain.removeHandler('workbench:request');
      ipcMain.handle('workbench:request', (event, input) => {
        if (input.binary && /\/pdf\?/.test(input.path)) globalThis.__reviewPdfLoads.push(input.path);
        return original(event, input);
      });
    });
    await main.locator('.paper-card').getByRole('button', { name: '阅读', exact: true }).click();
    let reader = main;
    assert.equal(application.windows().length, 1);
    await reader.waitForFunction(() => document.querySelector('canvas[data-page-number="1"]')?.width > 0);
    await reader.getByTestId('reader-model-select').selectOption('fixture-B');
    await reader.waitForFunction(() => document.querySelector('[data-testid=reader-model-select]')?.value === 'fixture-B');
    await reader.screenshot({ path: path.join(output, 'three-panes.png') });
    const widths = () => reader.evaluate(() => {
      const width = selector => document.querySelector(selector).getBoundingClientRect().width;
      return { outline: width('.reader-outline'), paper: width('.reading-column'), chat: width('.chat-panel'), total: width('.reader-layout') };
    });
    const drag = async (id, distance) => {
      const box = await reader.getByTestId(id).boundingBox();
      assert.ok(box, `Missing splitter ${id}`);
      await reader.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
      await reader.mouse.down();
      await reader.mouse.move(box.x + box.width / 2 + distance, box.y + box.height / 2, { steps: 8 });
      await reader.mouse.up();
      await delay(750);
    };
    await reader.locator('.page-index').last().click();
    await reader.waitForFunction(() => document.querySelector('[aria-label="当前页码"]')?.value === '12');
    await delay(800);
    const initial = await widths();
    await drag('chat-resizer', -350);
    const widerChat = await widths();
    assert.ok(widerChat.chat > initial.chat + 300);
    assert.ok(widerChat.paper < initial.paper - 300);
    assert.ok(Math.abs(widerChat.outline - initial.outline) < 3);
    await drag('outline-resizer', 40);
    const widerOutline = await widths();
    assert.ok(widerOutline.outline > widerChat.outline + 20);
    assert.equal(await reader.getByLabel('当前页码').inputValue(), '12', 'Resizing must retain the current reading page');
    await reader.getByTestId('outline-resizer').focus();
    await reader.keyboard.press('ArrowRight');
    await delay(500);
    assert.ok((await widths()).outline > widerOutline.outline + 4);
    await reader.getByTestId('toggle-outline').click();
    await reader.getByTestId('toggle-chat').click();
    assert.equal(await reader.locator('.reader-outline').isVisible(), false);
    assert.equal(await reader.locator('.chat-panel').isVisible(), false);
    const focus = await widths();
    assert.ok(focus.paper >= focus.total - 4, 'Hiding both panels must give the full area to the PDF');
    assert.equal(await reader.getByLabel('当前页码').inputValue(), '12');
    await reader.screenshot({ path: path.join(output, 'focus-reading.png') });
    await reader.getByTestId('toggle-chat').click();
    const input = reader.getByLabel('向当前文献提问');
    await input.fill('隐藏面板仍需完成回答');
    await reader.getByRole('button', { name: /发送/ }).click();
    await reader.getByTestId('streaming-answer').getByText(/第一段已收到/).waitFor();
    await input.fill('隐藏前保留的下一条草稿');
    await reader.evaluate(() => { window.__reviewChatPanel = document.querySelector('.chat-panel'); });
    await reader.getByTestId('toggle-chat').click();
    assert.equal(await reader.locator('.chat-panel').isVisible(), false);
    for (let i = 0; i < 100 && !fixture.sessions[0]?.completed; i++) await delay(50);
    assert.equal(fixture.sessions[0].completed, true, 'Hiding chat must not cancel its upstream stream');
    assert.equal(fixture.sessions[0].closedEarly, false);
    await reader.getByTestId('toggle-chat').click();
    assert.ok(await reader.evaluate(() => window.__reviewChatPanel === document.querySelector('.chat-panel')), 'Hiding a panel must not unmount it');
    await reader.getByRole('button', { name: '停止生成', exact: true }).waitFor({ state: 'hidden' });
    assert.equal(await input.inputValue(), '隐藏前保留的下一条草稿');
    await reader.locator('.chat-message.assistant .katex').first().waitFor();
    const font = await reader.locator('.chat-message.assistant .message-content').evaluate(element => Number.parseFloat(getComputedStyle(element).fontSize));
    const inputFont = await input.evaluate(element => Number.parseFloat(getComputedStyle(element).fontSize));
    const settingFont = await main.getByTestId('library-tab').evaluate(element => Number.parseFloat(getComputedStyle(element).fontSize));
    assert.ok(font >= 18 && inputFont >= 16 && settingFont >= 15, `Unreadable font sizes: chat=${font}, input=${inputFont}, navigation=${settingFont}`);
    assert.equal(fixture.requests.length, 1);
    assert.equal(fixture.requests[0].model, 'fixture-B');
    assert.equal(fixture.requests[0].path, fixture.requestPath);
    await main.evaluate(() => {
      const key = 'paper-workbench.reader-layout.v1';
      const layout = JSON.parse(localStorage.getItem(key));
      localStorage.setItem(key, JSON.stringify({ ...layout, chatWidth: layout.chatWidth + 40, outlineVisible: true }));
      window.dispatchEvent(new StorageEvent('storage', { key }));
    });
    await reader.locator('.reader-outline').waitFor({ state: 'visible' });
    await delay(750);
    assert.equal(await reader.getByLabel('当前页码').inputValue(), '12', 'A layout storage event must retain the current reading page');
    assert.equal(await input.inputValue(), '隐藏前保留的下一条草稿');
    await reader.getByTestId('toggle-outline').click();
    await delay(500);
    await reader.screenshot({ path: path.join(output, 'wide-assistant.png') });
    const saved = await widths();
    const modelBeforeRestart = await reader.getByTestId('reader-model-select').inputValue();
    const beforeResizeLoads = await application.evaluate(() => globalThis.__reviewPdfLoads);
    pdfLoads.push(...beforeResizeLoads);
    assert.equal(pdfLoads.length, 1, 'Resizing and hiding panels must not refetch the loaded PDF');
    await application.close();
    application = await _electron.launch(options);
    main = await application.firstWindow();
    await main.getByRole('button', { name: '设置', exact: true }).waitFor();
    reader = main;
    reader.on('pageerror', error => errors.push(error.message));
    await reader.getByTestId('toggle-chat').waitFor();
    await reader.waitForFunction(() => document.querySelector('[aria-label="当前页码"]')?.value === '12');
    assert.equal(await reader.locator('.reader-outline').isVisible(), false);
    assert.equal(await reader.locator('.chat-panel').isVisible(), true);
    const restored = await widths();
    assert.ok(Math.abs(restored.chat - saved.chat) < 4, 'Panel size must persist across application restart');
    assert.equal(await reader.getByTestId('reader-model-select').inputValue(), modelBeforeRestart);
    assert.equal(fixture.requests.length, 1, 'Restart must display the saved chat without asking the model again');
    await reader.getByTestId('toggle-outline').click();
    await application.evaluate(({ BrowserWindow }) => {
      const window = BrowserWindow.getAllWindows()[0];
      window.setSize(1040, 760);
    });
    await delay(1000);
    const narrow = await reader.evaluate(() => ({ viewport: window.innerWidth, scroll: document.documentElement.scrollWidth }));
    assert.ok(narrow.scroll <= narrow.viewport + 2, 'The reader must not overflow the desktop window');
    for (const label of ['放大 PDF', '缩小 PDF', '当前页码']) {
      const box = await reader.getByLabel(label, { exact: true }).boundingBox();
      assert.ok(box && box.x >= 0 && box.x + box.width <= narrow.viewport + 2, `Global control clipped: ${label}`);
    }
    assert.equal(await reader.getByLabel('当前页码').inputValue(), '12');
    await drag('chat-resizer', -800);
    const clamped = await widths();
    assert.ok(clamped.paper >= 320 && clamped.chat >= 280 && clamped.outline >= 140, 'Pane minimums must remain usable');
    assert.equal(errors.length, 0, errors.join('\n'));
    fs.writeFileSync(path.join(output, 'result.json'), JSON.stringify({ result: 'passed', version: require(path.join(root, 'package.json')).version, seconds: (Date.now() - started) / 1000, modelRequests: fixture.modelRequests, aiRequests: fixture.requests.length, initial, widerChat, widerOutline, focus, saved, restored, clamped, font, inputFont, settingFont, pdfRefetches: pdfLoads.length - 1, errors }, null, 2));
    console.log(JSON.stringify({ result: 'passed', output }));
  } catch (error) {
    fs.writeFileSync(path.join(output, 'failure.txt'), String(error.stack || error));
    if (application) await (await application.firstWindow()).screenshot({ path: path.join(output, 'failure.png') }).catch(() => undefined);
    throw error;
  } finally {
    if (application) await application.close();
    fixture.server.closeAllConnections();
    await new Promise(resolve => fixture.server.close(resolve));
    const cleaned = spawnSync(path.join(root, '.venv/Scripts/python.exe'), ['-B', '-c', 'from backend.ai import credential_service; import keyring; service=credential_service(); keyring.delete_password(service,"api-key") if keyring.get_password(service,"api-key") else None'], { cwd: root, env: { ...process.env, WORKBENCH_DATA_DIR: dataRoot }, encoding: 'utf8' });
    if (cleaned.status !== 0) throw new Error('Test credential cleanup failed');
  }
})();
