// Native QA of classification and provider model discovery using isolated D-drive data.
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { _electron } = require('playwright');
const { createToolsFixture } = require('./fixture_tools_api.cjs');
const root = path.resolve(__dirname, '..');
const output = path.join(root, '.review', `folders-models-${Date.now()}`);
const dataRoot = path.join(output, 'data');
const temp = path.join(output, 'temp');
fs.mkdirSync(temp, { recursive: true });
const seed = spawnSync(path.join(root, '.venv/Scripts/python.exe'), ['-B', '-m', 'review.seed_reader_fixture', dataRoot], { cwd: root, env: { ...process.env, WORKBENCH_DATA_DIR: dataRoot, TEMP: temp, TMP: temp, PYTHONIOENCODING: 'utf-8' }, encoding: 'utf8' });
assert.equal(seed.status, 0, seed.stderr);
const seeded = JSON.parse(seed.stdout.trim());
const digest = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const sourceHash = digest(seeded.source);
const paperFolder = path.join(dataRoot, 'papers', seeded.paper_id);
const pdfHashes = Object.fromEntries(fs.readdirSync(paperFolder).filter(name => name.endsWith('.pdf')).map(name => [name, digest(path.join(paperFolder, name))]));

(async () => {
  const fixture = await createToolsFixture();
  let application;
  const errors = [];
  const started = Date.now();
  try {
    const env = { ...process.env, WORKBENCH_DATA_DIR: dataRoot, TEMP: temp, TMP: temp };
    delete env.ELECTRON_RUN_AS_NODE;
    delete env.WORKBENCH_DEV;
    const options = { cwd: root, env, timeout: 90000 };
    if (process.env.REVIEW_EXECUTABLE) Object.assign(options, { executablePath: process.env.REVIEW_EXECUTABLE, args: [] });
    else Object.assign(options, { executablePath: path.join(root, 'node_modules/electron/dist/electron.exe'), args: ['.'] });
    application = await _electron.launch(options);
    const version = await application.evaluate(({ app }) => app.getVersion());
    if (process.env.REVIEW_EXECUTABLE) assert.equal(version, '0.11.0');
    let main = await application.firstWindow();
    main.on('pageerror', error => errors.push(error.message));
    await main.getByRole('button', { name: 'AI 设置', exact: true }).waitFor();
    await main.evaluate(address => window.workbench.request({ path: '/settings', method: 'PUT', body: { base_url: address, model: 'fixture-A', api_key: 'review-only-tools-key' } }), fixture.apiUrl);
    await main.getByRole('button', { name: '新建文件夹', exact: true }).click();
    await main.getByLabel('文件夹名称', { exact: true }).fill('实验设计');
    await main.getByRole('button', { name: '保存', exact: true }).click();
    await main.getByRole('button', { name: '实验设计', exact: true }).waitFor();
    const folders = await main.evaluate(() => window.workbench.request({ path: '/folders' }));
    assert.equal(folders.length, 1);
    const folder = folders[0];
    await main.getByRole('button', { name: '全部文献', exact: true }).click();
    await main.locator('.paper-card').getByLabel('移动文献到文件夹', { exact: true }).selectOption(folder.id);
    await main.waitForFunction(id => document.querySelector('.paper-card select[aria-label="移动文献到文件夹"]')?.value === id, folder.id);
    await main.getByRole('button', { name: '未分类', exact: true }).click();
    await main.waitForFunction(() => document.querySelectorAll('.paper-card').length === 0);
    await main.getByRole('button', { name: '实验设计', exact: true }).click();
    await main.locator('.paper-card').waitFor();
    await main.getByRole('button', { name: '重命名文件夹', exact: true }).click();
    await main.getByLabel('文件夹名称', { exact: true }).fill('方法论文');
    await main.getByRole('button', { name: '保存', exact: true }).click();
    await main.getByRole('button', { name: '方法论文', exact: true }).waitFor();
    await main.screenshot({ path: path.join(output, 'folders.png') });
    await main.getByLabel('搜索文献').fill('不存在的标题');
    await main.waitForFunction(() => document.querySelectorAll('.paper-card').length === 0);
    await main.getByLabel('搜索文献').fill('');
    await main.locator('.paper-card').waitFor();

    await main.getByRole('button', { name: 'AI 设置', exact: true }).click();
    await main.locator('.advanced-model-url > summary').click();
    await main.getByLabel('模型列表地址', { exact: true }).fill(fixture.modelsUrl);
    await main.getByRole('button', { name: '获取模型列表', exact: true }).click();
    await main.getByRole('checkbox', { name: 'mimo-v6pro', exact: true }).check();
    await main.getByRole('checkbox', { name: 'fixture-B', exact: true }).check();
    await main.getByRole('button', { name: '添加所选模型', exact: true }).click();
    await main.getByLabel('添加模型', { exact: true }).fill('manual-model');
    await main.getByRole('button', { name: '手动添加', exact: true }).click();
    await main.getByRole('button', { name: '保存设置', exact: true }).click();
    await main.getByRole('status').filter({ hasText: 'AI 服务设置已保存。' }).waitFor();
    const settings = await main.evaluate(() => window.workbench.request({ path: '/settings' }));
    assert.equal(settings.base_url, fixture.apiUrl);
    assert.equal(settings.model, 'fixture-A');
    assert.equal(settings.models_url, fixture.modelsUrl);
    for (const model of ['fixture-B', 'mimo-v6pro', 'manual-model']) assert.ok(settings.model_options.includes(model));
    assert.equal(fixture.modelRequests.length, 1);
    assert.ok(fixture.modelRequests[0].authorized);
    assert.equal(fixture.requests.length, 0, 'Listing models must not make chat or per-model test calls');
    await main.screenshot({ path: path.join(output, 'models.png') });
    await main.getByTestId('library-tab').click();
    await main.locator('.paper-card').getByRole('button', { name: '阅读', exact: true }).click();
    let reader = main;
    assert.equal(application.windows().length, 1, 'Reader must stay in the main window');
    await reader.getByLabel('当前 AI 模型', { exact: true }).selectOption('mimo-v6pro');
    await reader.waitForFunction(() => document.querySelector('[aria-label="当前 AI 模型"]')?.value === 'mimo-v6pro');
    await reader.getByLabel('向当前文献提问').fill('详细总结一下这篇文献');
    await reader.getByRole('button', { name: /发送/ }).click();
    await reader.locator('.chat-message.assistant').waitFor({ timeout: 60000 });
    await reader.getByLabel('停止生成').waitFor({ state: 'hidden' });
    assert.equal(fixture.requests.length, 2);
    assert.ok(fixture.requests.every(request => request.model === 'mimo-v6pro' && request.path === fixture.requestPath));
    assert.ok(fixture.requests[1].messages.every(message => typeof message.content === 'string'));
    assert.equal(fixture.requests[1].tools, undefined);
    assert.ok((await reader.locator('.chat-message.assistant').innerText()).includes('137'));
    await application.close();
    application = await _electron.launch(options);
    main = await application.firstWindow();
    await main.getByTestId('library-tab').click();
    await main.getByRole('button', { name: '方法论文', exact: true }).waitFor();
    await main.getByRole('button', { name: '方法论文', exact: true }).click();
    await main.locator('.paper-card').waitFor();
    const after = await main.evaluate(id => window.workbench.request({ path: `/papers/${id}` }), seeded.paper_id);
    assert.equal(after.folder_id, folder.id);
    assert.equal(after.model_override, 'mimo-v6pro');
    let confirmation = main.waitForEvent('dialog');
    let click = main.getByRole('button', { name: '删除文件夹', exact: true }).click();
    let dialog = await confirmation;
    assert.match(dialog.message(), /未分类|保留|不会删除/);
    await dialog.dismiss();
    await click;
    assert.equal((await main.evaluate(() => window.workbench.request({ path: '/folders' }))).length, 1);
    confirmation = main.waitForEvent('dialog');
    click = main.getByRole('button', { name: '删除文件夹', exact: true }).click();
    dialog = await confirmation;
    await dialog.accept();
    await click;
    await main.getByRole('button', { name: '未分类', exact: true }).click();
    await main.locator('.paper-card').waitFor();
    const preserved = await main.evaluate(id => window.workbench.request({ path: `/papers/${id}` }), seeded.paper_id);
    assert.equal(await main.locator('.error-notice').count(), 0, 'Folder deletion must not refresh the removed folder and show a false error');
    assert.equal(preserved.folder_id, null);
    assert.ok(preserved.can_read);
    assert.equal((await main.evaluate(id => window.workbench.request({ path: `/papers/${id}/chat` }), seeded.paper_id)).length, 2);
    assert.equal(digest(seeded.source), sourceHash);
    for (const [name, expected] of Object.entries(pdfHashes)) assert.equal(digest(path.join(paperFolder, name)), expected, 'Classification must preserve every PDF');
    assert.equal(errors.length, 0, errors.join('\n'));
    fs.writeFileSync(path.join(output, 'result.json'), JSON.stringify({ result: 'passed', version, seconds: (Date.now()-started)/1000, seeded, folders: 1, modelRequests: fixture.modelRequests, requests: fixture.requests.length, settings, pdfHashes, errors }, null, 2));
    fs.writeFileSync(path.join(output, 'requests.json'), JSON.stringify(fixture.requests, null, 2));
    console.log(JSON.stringify({ result: 'passed', output }));
  } catch (error) {
    fs.writeFileSync(path.join(output, 'failure.txt'), String(error.stack || error));
    if (application) await (await application.firstWindow()).screenshot({ path: path.join(output, 'failure.png') }).catch(() => undefined);
    throw error;
  } finally {
    if (application) await application.close();
    await new Promise(resolve => fixture.server.close(resolve));
    const cleaned = spawnSync(path.join(root, '.venv/Scripts/python.exe'), ['-B', '-c', 'from backend.ai import credential_service; import keyring; service=credential_service(); keyring.delete_password(service,"api-key") if keyring.get_password(service,"api-key") else None'], { cwd: root, env: { ...process.env, WORKBENCH_DATA_DIR: dataRoot }, encoding: 'utf8' });
    if (cleaned.status !== 0) throw new Error('Test credential cleanup failed');
  }
})();
