// Independent native QA: visible SSE, socket cancellation, math and PDF edges.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { _electron } = require('playwright');
const { createStreamFixture } = require('./fixture_stream_api.cjs');
const root = path.resolve(__dirname, '..');
const output = path.join(root, '.review', `stream-chat-${Date.now()}`);
const dataRoot = path.join(output, 'data');
const temp = path.join(output, 'temp');
fs.mkdirSync(temp, { recursive: true });
const prepared = spawnSync(path.join(root, '.venv/Scripts/python.exe'), ['-B', '-m', 'review.seed_reader_fixture', dataRoot, '--mixed'], { cwd: root, env: { ...process.env, WORKBENCH_DATA_DIR: dataRoot, TEMP: temp, TMP: temp, PYTHONIOENCODING: 'utf-8' }, encoding: 'utf8' });
assert.equal(prepared.status, 0, prepared.stderr);
const seeded = JSON.parse(prepared.stdout.trim());
const delay = time => new Promise(resolve => setTimeout(resolve, time));
async function until(check, message) {
  for (let i = 0; i < 100; i++) { if (await check()) return; await delay(50); }
  assert.fail(message);
}

(async () => {
  let application;
  const fixture = await createStreamFixture();
  const errors = [];
  const started = Date.now();
  try {
    const env = { ...process.env, WORKBENCH_DATA_DIR: dataRoot, TEMP: temp, TMP: temp };
    delete env.ELECTRON_RUN_AS_NODE;
    delete env.WORKBENCH_DEV;
    const options = { cwd: root, env, timeout: 90000, executablePath: process.env.REVIEW_EXECUTABLE || path.join(root, 'node_modules/electron/dist/electron.exe'), args: process.env.REVIEW_EXECUTABLE ? [] : ['.'] };
    application = await _electron.launch(options);
    const version = await application.evaluate(({ app }) => app.getVersion());
    assert.equal(version, '0.11.0');
    let main = await application.firstWindow();
    main.on('pageerror', error => errors.push(error.message));
    await main.getByRole('button', { name: 'AI 设置', exact: true }).waitFor();
    await main.evaluate(address => window.workbench.request({ path: '/settings', method: 'PUT', body: { base_url: address, model: 'stream-fixture', api_key: 'review-only-stream-key' } }), fixture.apiUrl);
    await main.locator('.paper-card').getByRole('button', { name: '阅读', exact: true }).click();
    let reader = main;
    assert.equal(application.windows().length, 1);
    await reader.waitForFunction(() => document.querySelector('canvas[data-page-number="1"]')?.width > 0 && document.querySelector('.textLayer')?.textContent.includes('137'));
    await reader.waitForFunction(() => document.querySelector('[data-testid=reader-model-select]')?.value === 'stream-fixture');
    const input = reader.getByLabel('向当前文献提问');
    await input.fill('保留原始输入');
    await reader.evaluate(() => {
      const span = [...document.querySelectorAll('.textLayer span')].find(node => node.textContent.includes('137'));
      const range = document.createRange(); range.selectNodeContents(span);
      window.getSelection().removeAllRanges(); window.getSelection().addRange(range);
      document.querySelector('.reading-column').dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));
    });
    assert.equal(await input.inputValue(), '保留原始输入', 'PDF selection must never overwrite the composer');
    assert.ok(await reader.evaluate(() => window.getSelection().toString().includes('137')));
    const viewportBefore = await reader.locator('[data-testid=pdf-scroll]').boundingBox();
    const initialCanvasWidth = await reader.locator('canvas[data-page-number="1"]').evaluate(canvas => Number.parseFloat(canvas.style.width));
    for (let i = 0; i < 15; i++) await reader.getByLabel('放大 PDF').click();
    await reader.waitForFunction(() => document.querySelector('.zoom-controls')?.textContent.includes('250%'));
    await reader.waitForFunction(width => Math.abs(Number.parseFloat(document.querySelector('canvas[data-page-number="1"]').style.width) - width * 2.5) < 2, initialCanvasWidth);
    const edges = await reader.locator('[data-testid=pdf-scroll]').evaluate(async element => {
      await new Promise(resolve => requestAnimationFrame(resolve));
      const stage = element.querySelector('.pdf-page-stage');
      element.scrollLeft = 0;
      const start = stage.getBoundingClientRect();
      const viewport = element.getBoundingClientRect();
      element.scrollLeft = element.scrollWidth;
      const end = stage.getBoundingClientRect();
      const result = { left: start.left, right: end.right, viewportLeft: viewport.left, viewportRight: viewport.right, width: element.clientWidth, scrollWidth: element.scrollWidth, scrollLeft: element.scrollLeft };
      element.scrollLeft = 0;
      return result;
    });
    assert.ok(edges.scrollWidth > edges.width + 200);
    assert.ok(edges.left >= edges.viewportLeft, 'At horizontal origin the PDF left edge must be reachable');
    assert.ok(edges.right <= edges.viewportRight + 2, 'At horizontal maximum the PDF right edge must be reachable');
    const viewportAfter = await reader.locator('[data-testid=pdf-scroll]').boundingBox();
    assert.ok(Math.abs(viewportAfter.width - viewportBefore.width) < 2, 'Zoom must not resize the available scroll viewport');
    await reader.screenshot({ path: path.join(output, 'zoom-left-edge.png') });
    const send = async question => { await input.fill(question); await reader.getByRole('button', { name: /发送/ }).click(); };
    const stop = reader.getByRole('button', { name: '停止生成', exact: true });
    const history = () => reader.evaluate(id => window.workbench.request({ path: `/papers/${id}/chat` }), seeded.paper_id);
    await send('流式与公式测试');
    await reader.getByTestId('streaming-reasoning').getByText(/思考第一段/).waitFor();
    await reader.getByTestId('streaming-answer').getByText(/第一段已收到/).waitFor();
    assert.ok(await stop.isVisible());
    assert.ok(!(await reader.getByTestId('streaming-answer').textContent()).includes('最后一段完成'));
    assert.equal(fixture.sessions[0].completed, false, 'First text must be visible before provider completion');
    await stop.waitFor({ state: 'hidden' });
    await reader.locator('.chat-message.assistant .katex').first().waitFor();
    assert.equal(await reader.locator('.chat-message.assistant .katex').count(), 4);
    assert.equal(await reader.locator('.chat-message.assistant pre code').textContent(), '\\(do not render code\\)\n');
    const firstHistory = await history();
    const firstAssistant = firstHistory.find(message => message.role === 'assistant');
    assert.equal(firstAssistant.status, 'completed');
    assert.ok(firstAssistant.reasoning.includes('思考第一段') && firstAssistant.reasoning.includes('思考第二段'));
    const font = await reader.locator('.chat-message.assistant .message-content').evaluate(element => Number.parseFloat(getComputedStyle(element).fontSize));
    const inputFont = await input.evaluate(element => Number.parseFloat(getComputedStyle(element).fontSize));
    assert.ok(font >= 16 && inputFont >= 15);
    await reader.screenshot({ path: path.join(output, 'math-and-reasoning.png') });
    const webToggle = reader.getByRole('checkbox', { name: '联网搜索', exact: true });
    assert.ok(await webToggle.isChecked());
    const beforeWeb = fixture.requests.length;
    await send('请联网搜索Python官方文档');
    await stop.waitFor({ state: 'hidden', timeout: 30000 });
    assert.equal(fixture.requests.length, beforeWeb + 2);
    const webTool = fixture.requests.at(-1).messages.find(message => message.role === 'tool');
    assert.ok(webTool && /python\.org/i.test(webTool.content), 'A real free search must return official Python results');
    assert.ok(!webTool.content.includes('image_url'));
    const webHistory = await history();
    const webSources = webHistory.at(-1).sources.filter(source => source.url);
    assert.ok(webSources.length > 0 && webSources.every(source => /^https?:\/\//.test(source.url) && source.title));
    await application.evaluate(({ shell }) => {
      globalThis.__reviewOpenedUrls = [];
      shell.openExternal = async url => { globalThis.__reviewOpenedUrls.push(url); };
    });
    const webLink = reader.locator('.chat-message.assistant').last().locator('.web-source-list button').first();
    await webLink.click();
    await until(async () => (await application.evaluate(() => globalThis.__reviewOpenedUrls)).length > 0, 'Web citation must open the source URL');
    const openedUrls = await application.evaluate(() => globalThis.__reviewOpenedUrls);
    assert.ok(openedUrls.length === 1 && webSources.some(source => source.url === openedUrls[0]));
    await webToggle.uncheck();
    await send('联网关闭测试');
    await stop.waitFor({ state: 'hidden', timeout: 15000 });
    assert.ok(!fixture.requests.at(-1).tools.some(tool => tool.function.name === 'web_search'));
    await webToggle.check();
    fixture.state.pause = true;
    await send('停止思考测试');
    await reader.getByTestId('streaming-reasoning').getByText(/思考第一段/).waitFor();
    const reasoningStopStart = Date.now();
    await stop.click();
    await stop.waitFor({ state: 'hidden', timeout: 5000 });
    await until(() => fixture.sessions.at(-1).closedEarly, 'Stopping reasoning must close the upstream socket');
    const reasoningStopMs = Date.now() - reasoningStopStart;
    fixture.state.pause = false;
    const afterReasoning = await history();
    assert.notEqual(afterReasoning.at(-1).status, 'completed');
    assert.ok(afterReasoning.at(-1).reasoning.includes('思考第一段'));
    fixture.state.pauseContent = true;
    await send('停止回答测试');
    await reader.getByTestId('streaming-answer').getByText(/第一段已收到/).waitFor();
    await stop.click();
    await stop.waitFor({ state: 'hidden', timeout: 5000 });
    await until(() => fixture.sessions.at(-1).closedEarly, 'Stopping content must close the upstream socket');
    fixture.state.pauseContent = false;
    const afterPartial = await history();
    assert.notEqual(afterPartial.at(-1).status, 'completed');
    assert.ok(afterPartial.at(-1).content.includes('第一段已收到'));
    fixture.state.pauseFullPrompt = true;
    const beforeSummary = fixture.requests.length;
    await send('详细总结一下这篇文献');
    await until(() => fixture.requests.length === beforeSummary + 2, 'Summary must be exactly a tool choice and a whole-paper stream');
    await reader.getByTestId('streaming-reasoning').getByText(/思考第二段/).waitFor();
    await stop.click();
    await stop.waitFor({ state: 'hidden', timeout: 5000 });
    await until(() => fixture.sessions.at(-1).closedEarly, 'Summary cancellation must close the whole-paper socket');
    fixture.state.pauseFullPrompt = false;
    const summaryRequest = fixture.requests.at(-1);
    assert.equal(summaryRequest.tools, undefined);
    assert.ok(summaryRequest.messages.every(message => typeof message.content === 'string'));
    assert.ok(summaryRequest.messages.some(message => message.content.includes('137 independent samples') && message.content.includes('811')));
    const runs = await reader.evaluate(id => window.workbench.request({ path: `/papers/${id}/analysis` }), seeded.paper_id);
    assert.ok(runs.length > 0 && runs.every(run => run.status !== 'running'));
    const beforeResume = fixture.requests.length;
    await reader.getByRole('button', { name: '继续总结', exact: true }).click();
    await stop.waitFor({ state: 'hidden', timeout: 15000 });
    assert.equal(fixture.requests.length, beforeResume + 1, 'Resuming a whole-paper run must stream one complete-body request');
    assert.deepEqual(fixture.requests.at(-1).messages, summaryRequest.messages);
    fixture.state.pause = true;
    await send('重复打开同一文献仍可取消');
    await reader.getByTestId('streaming-reasoning').getByText(/思考第一段/).waitFor();
    const firstSession = fixture.sessions.length - 1;
    await main.getByTestId('library-tab').click();
    await main.locator('.paper-card').getByRole('button', { name: '阅读', exact: true }).click();
    assert.equal(await main.getByTestId(`paper-tab-${seeded.paper_id}`).count(), 1);
    assert.equal(application.windows().length, 1, 'Opening the same paper must focus its tab');
    await stop.click();
    await stop.waitFor({ state: 'hidden', timeout: 5000 });
    await until(() => fixture.sessions[firstSession].closedEarly, 'Stop in a deduplicated tab must close its original stream');
    fixture.state.pause = false;
    fixture.state.closeBeforeFinish = true;
    await send('中断连接测试');
    await stop.waitFor({ state: 'hidden', timeout: 15000 });
    const failedHistory = await history();
    assert.notEqual(failedHistory.at(-1).status, 'completed', 'Abrupt EOF may not become a successful answer');
    fixture.state.closeBeforeFinish = false;
    const requestsBeforeRestart = fixture.requests.length;
    const saved = await history();
    await delay(500);
    await application.close();
    application = await _electron.launch(options);
    main = await application.firstWindow();
    await main.getByRole('button', { name: 'AI 设置', exact: true }).waitFor();
    reader = main;
    await reader.locator('.chat-message.assistant').first().waitFor();
    const restored = await reader.evaluate(id => window.workbench.request({ path: `/papers/${id}/chat` }), seeded.paper_id);
    assert.deepEqual(restored, saved, 'Reasoning and partial statuses must persist across full restart');
    assert.equal(fixture.requests.length, requestsBeforeRestart);
    assert.ok(fixture.requests.every(request => request.stream === true && request.path === fixture.requestPath && request.model === 'stream-fixture'));
    assert.equal(errors.length, 0, errors.join('\n'));
    fs.writeFileSync(path.join(output, 'requests.json'), JSON.stringify(fixture.requests, null, 2));
    fs.writeFileSync(path.join(output, 'result.json'), JSON.stringify({ result: 'passed', version, seconds: (Date.now() - started) / 1000, seeded, edges, font, inputFont, reasoningStopMs, webSources, openedUrls, requests: fixture.requests.length, sessions: fixture.sessions, messages: saved.length, errors }, null, 2));
    console.log(JSON.stringify({ result: 'passed', output }));
  } catch (error) {
    fs.writeFileSync(path.join(output, 'failure.txt'), String(error.stack || error));
    fs.writeFileSync(path.join(output, 'failed-sessions.json'), JSON.stringify(fixture.sessions, null, 2));
    if (application) await (await application.firstWindow()).screenshot({ path: path.join(output, 'failure.png') }).catch(() => undefined);
    throw error;
  } finally {
    if (application) await application.close();
    fixture.server.closeAllConnections();
    await new Promise(resolve => fixture.server.close(resolve));
    const cleaned = spawnSync(path.join(root, '.venv/Scripts/python.exe'), ['-B', '-c', 'from backend.ai import credential_service; import keyring; service=credential_service(); keyring.delete_password(service,"api-key") if keyring.get_password(service,"api-key") else None'], { cwd: root, env: { ...process.env, WORKBENCH_DATA_DIR: dataRoot }, encoding: 'utf8' });
    if (cleaned.status !== 0) throw new Error('Test credential cleanup failed');
  }
})();
